name = "YaXLSX"
uuid = "9db3cc25-22fb-4fcf-aa4a-955ead6cf264"
authors = ["alexklo9339@gmail.com"]
version = "1.0.0-DEV"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
