name: Documenter

on:
  push:
    branches:
      - main

jobs:
  Documenter:
    permissions:
      contents: write
      statuses: write
      actions: write
      pull-requests: write
    name: Documentatio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install dependencies
      run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(; path = pwd())); Pkg.instantiate();'

    - name: Build documentation
      run: julia --project=docs docs/make.jl

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
